# Generated by Django 4.2 on 2023-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_todolist_completion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completion_at',
            field=models.DateField(blank=True),
        ),
    ]
